server:
  port: 1111
spring:
  application:
    name: helloMybatis
  datasource:
    name: mybatis-test
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://116.62.166.188:3306/demo?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.wefed.mybatis.dao